import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const LINKS = [
  { href: "/", label: "Home" },
  { href: "/todos", label: "Todos" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex items-center justify-center gap-10">
              {LINKS.map((link) => (
                <Link key={link.href} href={link.href}>
                  <li className="text-blue-500">{link.label}</li>
                </Link>
              ))}
            </ul>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
